sjl:
  applicationClass: com.vga.sjl.demo.headless.HeadlessApplication
  arguments:
    common:
      - --add-opens=java.base/java.io=ALL-UNNAMED
    start:
      - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
tomcat:
  port: 8080