sjl:
  applicationClass: com.vga.sjl.updater.UpdaterApplication
  controlPort: 21567
  arguments:
    common:
      - --add-opens=java.base/java.io=ALL-UNNAMED
      - -Dlogback.configurationFile=logback.xml
tomcat:
  port: 8081

app:
  executable: /home/avramenko/IdeaProjects/own/simple-java-launcher/examples/headless-app/build/dist2/headless-app
  libFolder: /home/avramenko/IdeaProjects/own/simple-java-launcher/examples/headless-app/build/dist2/lib
  tempFolder: /home/avramenko/IdeaProjects/own/simple-java-launcher/examples/headless-app/build/dist2/temp